import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { materializeExactSequence } from "../src/exact-sequence.js";
import { Memory, ensureRootBasis, type LinkHandle, type RootBasis } from "../src/memory.js";
import { defineStructuralRoleDictionary, defineStructuralRule } from "../src/structural-rule.js";

function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(`v0.13 A62 Rule publication history: ${m}`);}
function same<T>(a:T,e:T,m:string):void{assert(Object.is(a,e),`${m}: values differ`);}
function freezeChain(memory:Memory,values:readonly LinkHandle[]):LinkHandle{let body=memory.root;for(let i=values.length-1;i>=0;i-=1)body=memory.ensure(values[i]!,body);return memory.ensureStartSelfClosed(body);}
function readChain(memory:Memory,envelope:LinkHandle,kind:string):readonly LinkHandle[]{const e=memory.poles(envelope);assert(e.start===envelope&&e.end!==envelope,`A21 ${kind} envelope`);const out:LinkHandle[]=[],seen=new Set<LinkHandle>();let cursor=e.end;while(cursor!==memory.root){assert(!seen.has(cursor),`A21 ${kind} cycle`);seen.add(cursor);const p=memory.poles(cursor);out.push(p.start);cursor=p.end;}return Object.freeze(out);}
function step(memory:Memory,executionRoot:LinkHandle,schedule:"forward"|"reverse"):LinkHandle{const execution=memory.poles(executionRoot),context=execution.start,frontierEnvelope=execution.end;const authorityEnvelope=memory.poles(context).end,continuations=[...readChain(memory,authorityEnvelope,"authority")],occurrences=[...readChain(memory,frontierEnvelope,"frontier")];if(schedule==="reverse")occurrences.reverse();let nextBody=memory.root;for(const occurrence of occurrences){const truth=memory.poles(memory.poles(occurrence).end);assert(truth.start===context,"A21 occurrence carries current-context truth");for(const continuation of continuations){const p=memory.poles(continuation);if(p.start!==truth.end)continue;const nextTruth=memory.ensure(context,p.end),childOccurrence=memory.ensure(occurrence,nextTruth);nextBody=memory.ensure(childOccurrence,nextBody);}}return memory.ensure(context,memory.ensureStartSelfClosed(nextBody));}
function frontierTruthEnds(memory:Memory,E:LinkHandle):readonly LinkHandle[]{const ep=memory.poles(E),out:LinkHandle[]=[];for(const occurrence of readChain(memory,ep.end,"frontier")){const truth=memory.poles(memory.poles(occurrence).end);same(truth.start,ep.start,"A62 frontier context");out.push(truth.end);}return Object.freeze(out);}

interface RuleFixture{readonly rule:LinkHandle;}
function ruleFixture(memory:Memory,b:RootBasis,seed:LinkHandle):RuleFixture{const marker=memory.ensure(seed,b.U),r0=memory.ensure(marker,b.O),r1=memory.ensure(r0,b.C),pair=memory.ensure(r0,r1),body=materializeExactSequence(memory,[pair]);const dictionary=defineStructuralRoleDictionary(memory,[r0,r1]);return Object.freeze({rule:defineStructuralRule(memory,dictionary,body)});}
function initialCatalog(memory:Memory,context:LinkHandle):LinkHandle{return memory.ensure(context,memory.root);}
function publishVersion(memory:Memory,catalog:LinkHandle,rule:LinkHandle):LinkHandle{const cp=memory.poles(catalog),membership=memory.ensure(cp.start,rule),occurrence=memory.ensure(cp.end,membership);return memory.ensure(cp.start,occurrence);}
function selectedRequest(memory:Memory,context:LinkHandle,catalog:LinkHandle,rule:LinkHandle):LinkHandle{return memory.ensure(context,memory.ensure(catalog,rule));}

interface EqualityCheck{readonly gate:LinkHandle;readonly query:LinkHandle;}
function equalityCheck(memory:Memory,stage:LinkHandle,expected:LinkHandle,actual:LinkHandle):EqualityCheck{const es=memory.ensure(stage,expected),as=memory.ensure(stage,actual),gate=memory.ensureStartSelfClosed(es);return Object.freeze({gate,query:memory.ensure(gate,as)});}
interface PublicationProgram{readonly E0:LinkHandle;readonly depth:number;readonly accepted:LinkHandle;}
function compilePublicationHistoryProof(memory:Memory,requestTruth:LinkHandle):PublicationProgram{const truth=memory.poles(requestTruth),parentContext=truth.start,request=memory.poles(truth.end),catalog=request.start,requestedRule=request.end,cp=memory.poles(catalog);assert(cp.end!==memory.root,"A62 selected catalog contains prior publication occurrence");const head=memory.poles(cp.end),membership=memory.poles(head.end),publishedRule=membership.end;let stage=memory.ensure(requestTruth,memory.root);const check=(expected:LinkHandle,actual:LinkHandle):EqualityCheck=>{stage=memory.ensure(stage,memory.ensure(expected,actual));return equalityCheck(memory,stage,expected,actual);};const checks=[check(cp.start,membership.start),check(requestedRule,publishedRule)];const transitions=checks.map((x,i)=>memory.ensure(x.gate,checks[i+1]?.query??requestedRule)),K=memory.ensure(parentContext,freezeChain(memory,transitions)),seed=memory.ensure(K,checks[0]!.query);return Object.freeze({E0:memory.ensure(K,freezeChain(memory,[memory.ensure(memory.root,seed)])),depth:checks.length,accepted:requestedRule});}
function runPublicationProof(memory:Memory,requestTruth:LinkHandle):readonly LinkHandle[]{const p=compilePublicationHistoryProof(memory,requestTruth);let current=p.E0;for(let i=0;i<p.depth;i+=1)current=step(memory,current,"forward");return frontierTruthEnds(memory,current);}

function exercise(memory:Memory,noise:boolean):void{const b=ensureRootBasis(memory);if(noise)memory.ensure(memory.ensure(b.U,b.C),b.O);const c=memory.ensure(b.O,b.C),exec=memory.ensure(b.R,b.U),r1=ruleFixture(memory,b,memory.ensure(b.U,b.L)).rule,r2=ruleFixture(memory,b,memory.ensure(b.C,b.L)).rule;assert(r1!==r2,"A62 rules distinct");const catalog0=initialCatalog(memory,c),catalog1=publishVersion(memory,catalog0,r1);
let out=runPublicationProof(memory,selectedRequest(memory,exec,catalog1,r1));same(out.length,1,"A62 prior published r1 accepted");same(out[0],r1,"A62 accepted exact r1");
out=runPublicationProof(memory,selectedRequest(memory,exec,catalog1,r2));same(out.length,0,"A62 r2 absent from selected prior history ZERO");
const ambientMembership=memory.ensure(c,r2);assert(ambientMembership!==memory.poles(memory.poles(catalog1).end).end,"A62 ambient membership outside selected history");out=runPublicationProof(memory,selectedRequest(memory,exec,catalog1,r2));same(out.length,0,"A62 ambient physical membership cannot authorize r2");
const frozenRequest=selectedRequest(memory,exec,catalog1,r2),frozenProgram=compilePublicationHistoryProof(memory,frozenRequest),frozenE0=frozenProgram.E0;const catalog2=publishVersion(memory,catalog1,r2);same(frozenProgram.E0,frozenE0,"A62 later publication cannot rewrite frozen proof program");out=runPublicationProof(memory,frozenRequest);same(out.length,0,"A62 later publication cannot backdate old catalog request");
out=runPublicationProof(memory,selectedRequest(memory,exec,catalog2,r2));same(out.length,1,"A62 explicit newer catalog publishes r2");same(out[0],r2,"A62 newer catalog exact r2");
out=runPublicationProof(memory,selectedRequest(memory,exec,catalog1,r1));same(out.length,1,"A62 old catalog remains immutable r1 authority");
const foreignContext=memory.ensure(b.C,b.U),foreignMembership=memory.ensure(foreignContext,r1),badHead=memory.ensure(memory.poles(catalog0).end,foreignMembership),badCatalog=memory.ensure(c,badHead);out=runPublicationProof(memory,selectedRequest(memory,exec,badCatalog,r1));same(out.length,0,"A62 foreign membership context ZERO");
const r3=ruleFixture(memory,b,memory.ensure(b.O,b.L)).rule;memory.ensure(r3,memory.ensure(b.L,b.U));out=runPublicationProof(memory,selectedRequest(memory,exec,catalog2,r3));same(out.length,0,"A62 publication-like scratch cannot authorize unrelated rule");
}

function staticGuards():void{const root=resolve(process.cwd(),".."),own=readFileSync(join(root,"ts/test/research-v013-rule-publication-history-a62.test.ts"),"utf8"),a35=readFileSync(join(root,"ts/test/research-v013-contextual-catalog-publication-a35.test.ts"),"utf8"),a36=readFileSync(join(root,"ts/test/research-v013-detachment-structural-admission-a36.test.ts"),"utf8"),a37=readFileSync(join(root,"ts/test/research-v013-link-carried-admission-program-a37.test.ts"),"utf8");const proof=own.slice(own.indexOf("function compilePublicationHistoryProof("),own.indexOf("\nfunction runPublicationProof(",own.indexOf("function compilePublicationHistoryProof(")));for(const x of ["memory.find(",".outgoing(",".incoming(","allLinks(","sourcePublishable","readStructuralRule","readStructuralRoleDictionary",".includes(","new Set","for(","while("])assert(!proof.includes(x),`A62 proof excludes ambient/external publication oracle ${x}`);assert(proof.includes("const head=memory.poles(cp.end)"),"A62 evidence comes from selected catalog head");assert(proof.includes("publishedRule=membership.end"),"A62 published Rule derived from selected occurrence");assert(a35.includes("memory.find(candidate, value)"),"A62 attacks A35 ambient existence query");assert(a35.includes("SOURCE_PUBLISHABLE_INTERPRETER=HOST_RESIDUAL"),"A62 inherits A35 residual marker");assert(a36.includes("PUBLICATION_EXISTENCE_SOURCE_REMOVED=NO"),"A62 attacks exact A36 prior-existence residual");const x=own.slice(own.indexOf("function step("),own.indexOf("\nfunction frontierTruthEnds(",own.indexOf("function step("))),y=a37.slice(a37.indexOf("function step("),a37.indexOf("\ninterface Program",a37.indexOf("function step(")));same(x.replace(/\s+/g,""),y.replace(/\s+/g,""),"A62 runtime source-identical A37/A21");}
function main():void{exercise(new Memory(),false);exercise(new Memory(),true);staticGuards();console.log(["MTS v0.13 A62: RULE_PUBLICATION_HISTORY=GREEN_SCOPED_RESEARCH","PRIOR_PUBLICATION_EVIDENCE=SELECTED_IMMUTABLE_CATALOG_VERSION","AMBIENT_MEMORY_EXISTENCE_QUERY=0 MEMORY_FIND_PUBLICATION_CHECK=0","SELECTED_CATALOG_HEAD=PRIOR_PUBLICATION_TOKEN","OLD_CATALOG_VERSION=IMMUTABLE","AMBIENT_RULE_MEMBERSHIP=INERT LATE_PUBLICATION_CANNOT_BACKDATE=YES","FOREIGN_MEMBERSHIP_CONTEXT=ZERO MISMATCHED_RULE=ZERO","PUBLICATION_EXISTENCE_SOURCE_REMOVED=YES_SCOPED_RULE_AUTHORITY","RULE_WELL_FORMED_ADMISSION=E2_E3_RESIDUAL PUBLICATION_EVENT_FORMATION=E3_RESIDUAL","GLOBAL_E2=OPEN GLOBAL_E3=OPEN GLOBAL_E4=OPEN FULL_SELF_HOSTED=FALSE","NEXT_BOUNDARY=A63_RULE_FORMATION_ADMISSIBILITY","V013_NOT_ACCEPTED PRODUCTION_UNCHANGED"].join(" "));}
main();
