import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { materializeExactSequence, readExactSequence } from "../src/exact-sequence.js";
import { Memory, ensureRootBasis, type LinkHandle, type RootBasis } from "../src/memory.js";
function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(`v0.13 A58 proof-carried equation START: ${m}`);}
function same<T>(a:T,e:T,m:string):void{assert(Object.is(a,e),`${m}: values differ`);}
function freeze(memory:Memory,xs:readonly LinkHandle[]):LinkHandle{let b=memory.root;for(let i=xs.length-1;i>=0;i-=1)b=memory.ensure(xs[i]!,b);return memory.ensureStartSelfClosed(b);}
function readChain(memory:Memory,e:LinkHandle,k:string):readonly LinkHandle[]{const p=memory.poles(e);assert(p.start===e&&p.end!==e,`A21 ${k} envelope`);const out:LinkHandle[]=[],seen=new Set<LinkHandle>();let c=p.end;while(c!==memory.root){assert(!seen.has(c),`A21 ${k} cycle`);seen.add(c);const q=memory.poles(c);out.push(q.start);c=q.end;}return Object.freeze(out);}
function step(memory:Memory,E:LinkHandle,schedule:"forward"|"reverse"):LinkHandle{const ep=memory.poles(E),K=ep.start,ap=memory.poles(K),cs=[...readChain(memory,ap.end,"authority")],os=[...readChain(memory,ep.end,"frontier")];if(schedule==="reverse")os.reverse();let body=memory.root;for(const o of os){const t=memory.poles(memory.poles(o).end);assert(t.start===K,"A21 occurrence context");for(const c of cs){const p=memory.poles(c);if(p.start!==t.end)continue;const nt=memory.ensure(K,p.end),no=memory.ensure(o,nt);body=memory.ensure(no,body);}}return memory.ensure(K,memory.ensureStartSelfClosed(body));}
function ends(memory:Memory,E:LinkHandle):readonly LinkHandle[]{const ep=memory.poles(E),out:LinkHandle[]=[];for(const o of readChain(memory,ep.end,"frontier")){const t=memory.poles(memory.poles(o).end);same(t.start,ep.start,"A58 frontier context");out.push(t.end);}return Object.freeze(out);}
interface Frame{readonly startRole:LinkHandle;readonly endRole:LinkHandle;}
function frame(memory:Memory,b:RootBasis):Frame{const whole=memory.ensure(b.L,b.L),startRole=memory.ensureStartSelfClosed(whole),endRole=memory.ensureEndSelfClosed(whole);assert(startRole!==endRole,"A58 frame roles distinct");return Object.freeze({startRole,endRole});}
interface RuleShape{readonly rule:LinkHandle;readonly roles:readonly LinkHandle[];readonly equations:readonly LinkHandle[];}
function roles(memory:Memory,b:RootBasis):readonly LinkHandle[]{const marker=memory.ensure(b.U,b.U);let x=memory.ensure(b.O,marker);const out:LinkHandle[]=[];for(let i=0;i<8;i+=1){x=memory.ensure(x,i%2===0?b.L:b.C);out.push(x);}return Object.freeze(out);}
function equation(memory:Memory,target:LinkHandle,start:LinkHandle,end:LinkHandle):LinkHandle{return memory.ensure(target,memory.ensure(start,end));}
function defineRule(memory:Memory,b:RootBasis,rr:boolean,re:boolean):RuleShape{const rs=roles(memory,b),eqs=Object.freeze([equation(memory,rs[3]!,rs[1]!,rs[2]!),equation(memory,rs[6]!,rs[3]!,rs[4]!),equation(memory,rs[7]!,rs[3]!,rs[5]!)]);return Object.freeze({rule:memory.ensure(materializeExactSequence(memory,rr?[...rs].reverse():rs),materializeExactSequence(memory,re?[...eqs].reverse():eqs)),roles:rs,equations:eqs});}
interface WitnessedEquation{readonly equation:LinkHandle;readonly witness:LinkHandle;}
function witnessedEquation(memory:Memory,f:Frame,target:LinkHandle,start:LinkHandle,end:LinkHandle):WitnessedEquation{const pair=memory.ensure(start,end),eq=memory.ensure(target,pair),sb=memory.ensure(f.startRole,target),eb=memory.ensure(f.endRole,pair),w=memory.ensure(memory.ensure(sb,eb),eq);return Object.freeze({equation:eq,witness:w});}
function realization(memory:Memory,inputs:readonly LinkHandle[],witnesses:readonly LinkHandle[]):LinkHandle{return memory.ensure(materializeExactSequence(memory,inputs),materializeExactSequence(memory,witnesses));}
function request(memory:Memory,K:LinkHandle,rule:LinkHandle,value:LinkHandle):LinkHandle{return memory.ensure(K,memory.ensure(rule,value));}
interface Node{readonly previous:LinkHandle;readonly value:LinkHandle;}
function node(memory:Memory,c:LinkHandle):Node{assert(c!==memory.root,"A58 sequence node");const p=memory.poles(c);assert(p.start===c,"A58 ExactSequence cell");const q=memory.poles(p.end);return Object.freeze({previous:q.start,value:q.end});}
function fold<S>(memory:Memory,c:LinkHandle,s:S,f:(s:S,v:LinkHandle)=>S):S{if(c===memory.root)return s;const n=node(memory,c);return f(fold(memory,n.previous,s,f),n.value);}
interface EqualityCheck{readonly gate:LinkHandle;readonly query:LinkHandle;}
function equality(memory:Memory,stage:LinkHandle,expected:LinkHandle,actual:LinkHandle):EqualityCheck{const es=memory.ensure(stage,expected),as=memory.ensure(stage,actual),gate=memory.ensureStartSelfClosed(es);return Object.freeze({gate,query:memory.ensure(gate,as)});}
interface EquationEvidence{readonly target:LinkHandle;readonly equation:LinkHandle;readonly checks:readonly EqualityCheck[];}
function readEquationEvidence(memory:Memory,f:Frame,witness:LinkHandle):EquationEvidence{
  const wp=memory.poles(witness),bp=memory.poles(wp.start),sb=memory.poles(bp.start),eb=memory.poles(bp.end);
  const target=sb.end,pair=eb.end,equationHandle=wp.end,reconstructed=memory.ensure(target,pair);
  let stage=memory.ensure(witness,memory.root);
  const check=(e:LinkHandle,a:LinkHandle)=>{stage=memory.ensure(stage,memory.ensure(e,a));return equality(memory,stage,e,a);};
  return Object.freeze({target,equation:equationHandle,checks:Object.freeze([check(f.startRole,sb.start),check(f.endRole,eb.start),check(reconstructed,equationHandle)])});
}
interface MatchSeed{readonly ancestry:LinkHandle;readonly body:LinkHandle;}
function add(memory:Memory,gate:LinkHandle,K:LinkHandle,s:MatchSeed,candidate:LinkHandle):MatchSeed{const q=memory.ensure(gate,candidate),t=memory.ensure(K,q),a=memory.ensure(s.ancestry,candidate),o=memory.ensure(a,t);return Object.freeze({ancestry:a,body:memory.ensure(o,s.body)});}
function finish(memory:Memory,expected:LinkHandle,s:MatchSeed,gate:LinkHandle,K:LinkHandle):LinkHandle{void expected;void gate;return step(memory,memory.ensure(K,memory.ensureStartSelfClosed(s.body)),"forward");}
function matchCarrier(memory:Memory,expected:LinkHandle,carrier:LinkHandle):LinkHandle{const gate=memory.ensureStartSelfClosed(expected),authority=freeze(memory,[memory.ensure(gate,memory.root)]),K=memory.ensure(memory.ensure(expected,authority),authority),s=fold<MatchSeed>(memory,carrier,Object.freeze({ancestry:memory.root,body:memory.root}),(z,v)=>add(memory,gate,K,z,v));return finish(memory,expected,s,gate,K);}
function matchRole(memory:Memory,f:Frame,expected:LinkHandle,inputs:LinkHandle,witnesses:LinkHandle):LinkHandle{const gate=memory.ensureStartSelfClosed(expected),authority=freeze(memory,[memory.ensure(gate,memory.root)]),K=memory.ensure(memory.ensure(expected,authority),authority),s0=fold<MatchSeed>(memory,inputs,Object.freeze({ancestry:memory.root,body:memory.root}),(z,v)=>add(memory,gate,K,z,v)),s1=fold<MatchSeed>(memory,witnesses,s0,(z,w)=>add(memory,gate,K,z,readEquationEvidence(memory,f,w).target));return finish(memory,expected,s1,gate,K);}
function matchEquation(memory:Memory,f:Frame,expected:LinkHandle,witnesses:LinkHandle):LinkHandle{const gate=memory.ensureStartSelfClosed(expected),authority=freeze(memory,[memory.ensure(gate,memory.root)]),K=memory.ensure(memory.ensure(expected,authority),authority),s=fold<MatchSeed>(memory,witnesses,Object.freeze({ancestry:memory.root,body:memory.root}),(z,w)=>add(memory,gate,K,z,readEquationEvidence(memory,f,w).equation));return finish(memory,expected,s,gate,K);}
interface OneCheck{readonly bodyGate:LinkHandle;readonly bodyQuery:LinkHandle;readonly truthGate:LinkHandle;readonly truthQuery:LinkHandle;}
function one(memory:Memory,E:LinkHandle,stage:LinkHandle):OneCheck{const ep=memory.poles(E),K=ep.start,en=memory.poles(ep.end),body=en.end,o=memory.poles(body).start,t=memory.poles(o).end,bs=memory.ensure(stage,memory.root),ts=memory.ensure(stage,bs),eb=memory.ensure(o,memory.root),sb=memory.ensure(bs,body),seb=memory.ensure(bs,eb),bg=memory.ensureStartSelfClosed(sb),bq=memory.ensure(bg,seb),et=memory.ensure(K,memory.root),st=memory.ensure(ts,t),set=memory.ensure(ts,et),tg=memory.ensureStartSelfClosed(set),tq=memory.ensure(tg,st);return Object.freeze({bodyGate:bg,bodyQuery:bq,truthGate:tg,truthQuery:tq});}
interface Coverage{readonly history:LinkHandle;readonly count:number;}
function addOne(memory:Memory,s:Coverage,E:LinkHandle):Coverage{const stage=memory.ensure(s.history,E),c=one(memory,E,stage),carrier=materializeExactSequence(memory,[c.bodyGate,c.bodyQuery,c.truthGate,c.truthQuery]);return Object.freeze({history:memory.ensure(s.history,carrier),count:s.count+1});}
function identityCoverage(memory:Memory,source:LinkHandle,candidates:LinkHandle,s:Coverage):Coverage{return fold<Coverage>(memory,source,s,(z,e)=>addOne(memory,z,matchCarrier(memory,e,candidates)));}
function roleForward(memory:Memory,f:Frame,ruleRoles:LinkHandle,inputs:LinkHandle,witnesses:LinkHandle,s:Coverage):Coverage{return fold<Coverage>(memory,ruleRoles,s,(z,e)=>addOne(memory,z,matchRole(memory,f,e,inputs,witnesses)));}
function targetReverse(memory:Memory,f:Frame,witnesses:LinkHandle,ruleRoles:LinkHandle,s:Coverage):Coverage{return fold<Coverage>(memory,witnesses,s,(z,w)=>addOne(memory,z,matchCarrier(memory,readEquationEvidence(memory,f,w).target,ruleRoles)));}
function equationForward(memory:Memory,f:Frame,ruleEquations:LinkHandle,witnesses:LinkHandle,s:Coverage):Coverage{return fold<Coverage>(memory,ruleEquations,s,(z,e)=>addOne(memory,z,matchEquation(memory,f,e,witnesses)));}
function equationReverse(memory:Memory,f:Frame,witnesses:LinkHandle,ruleEquations:LinkHandle,s:Coverage):Coverage{return fold<Coverage>(memory,witnesses,s,(z,w)=>addOne(memory,z,matchCarrier(memory,readEquationEvidence(memory,f,w).equation,ruleEquations)));}
function coverage(memory:Memory,f:Frame,rule:LinkHandle,value:LinkHandle):Coverage{const r=memory.poles(rule),v=memory.poles(value),s=Object.freeze({history:memory.root,count:0});return equationReverse(memory,f,v.end,r.end,equationForward(memory,f,r.end,v.end,targetReverse(memory,f,v.end,r.start,identityCoverage(memory,v.start,r.start,roleForward(memory,f,r.start,v.start,v.end,s)))));}
interface Assembly{readonly seed:LinkHandle;readonly body:LinkHandle;readonly count:number;}
function readOne(memory:Memory,c:LinkHandle):OneCheck{const q=readExactSequence(memory,c).values;same(q.length,4,"A58 OneCheck arity");return Object.freeze({bodyGate:q[0]!,bodyQuery:q[1]!,truthGate:q[2]!,truthQuery:q[3]!});}
function assembleCoverage(memory:Memory,h:LinkHandle,accepted:LinkHandle,body:LinkHandle=memory.root,count=0):Assembly{if(h===memory.root)return Object.freeze({seed:accepted,body,count});const p=memory.poles(h),c=readOne(memory,p.end);let b=memory.ensure(memory.ensure(c.truthGate,accepted),body);b=memory.ensure(memory.ensure(c.bodyGate,c.truthQuery),b);return assembleCoverage(memory,p.start,c.bodyQuery,b,count+1);}
interface ProofHistory{readonly history:LinkHandle;readonly count:number;}
function proofHistory(memory:Memory,f:Frame,witnesses:LinkHandle):ProofHistory{return fold<ProofHistory>(memory,witnesses,Object.freeze({history:memory.root,count:0}),(s,w)=>{let h=s.history,n=s.count;for(const c of readEquationEvidence(memory,f,w).checks){h=memory.ensure(h,memory.ensure(c.gate,c.query));n+=1;}return Object.freeze({history:h,count:n});});}
function prependProof(memory:Memory,h:LinkHandle,next:LinkHandle,body:LinkHandle,count=0):Assembly{if(h===memory.root)return Object.freeze({seed:next,body,count});const p=memory.poles(h),c=memory.poles(p.end),b=memory.ensure(memory.ensure(c.start,next),body);return prependProof(memory,p.start,c.end,b,count+1);}
interface Program{readonly E0:LinkHandle;readonly depth:number;readonly coverageChecks:number;readonly proofChecks:number;}
function compile(memory:Memory,f:Frame,selected:LinkHandle):Program{const sp=memory.poles(selected),parent=sp.start,p=memory.poles(sp.end),rule=p.start,value=p.end,v=memory.poles(value),cov=coverage(memory,f,rule,value),ca=assembleCoverage(memory,cov.history,value),ph=proofHistory(memory,f,v.end),all=prependProof(memory,ph.history,ca.seed,ca.body),authority=memory.ensureStartSelfClosed(all.body),K=memory.ensure(parent,authority),seed=memory.ensure(K,all.seed),E0=memory.ensure(K,freeze(memory,[memory.ensure(memory.root,seed)]));return Object.freeze({E0,depth:ca.count*2+all.count,coverageChecks:ca.count,proofChecks:all.count});}
function run(memory:Memory,p:Program):readonly LinkHandle[]{let E=p.E0;for(let i=0;i<p.depth;i+=1)E=step(memory,E,"forward");return ends(memory,E);}
function exercise(memory:Memory,noise:boolean):void{
  const b=ensureRootBasis(memory);if(noise)memory.ensure(memory.ensure(b.U,b.C),b.L);const f=frame(memory,b),forward=defineRule(memory,b,false,false),reverse=defineRule(memory,b,true,true),rs=forward.roles;
  const ws=Object.freeze([witnessedEquation(memory,f,rs[3]!,rs[1]!,rs[2]!),witnessedEquation(memory,f,rs[6]!,rs[3]!,rs[4]!),witnessedEquation(memory,f,rs[7]!,rs[3]!,rs[5]!)]),free=Object.freeze([rs[0]!,rs[1]!,rs[2]!,rs[4]!,rs[5]!]),valid=realization(memory,free,ws.map(x=>x.witness)),validRev=realization(memory,[...free].reverse(),[...ws].reverse().map(x=>x.witness)),K=memory.ensure(b.R,b.U);
  for(const rule of [forward.rule,reverse.rule])for(const value of [valid,validRev]){const p=compile(memory,f,request(memory,K,rule,value)),r=run(memory,p);same(p.coverageChecks,22,"A58 valid coverage checks");same(p.proofChecks,9,"A58 three proof gates per equation");same(r.length,1,"A58 valid singleton");same(r[0],value,"A58 valid accepted");}
  const forged=witnessedEquation(memory,f,rs[3]!,rs[1]!,rs[2]!),fp=memory.poles(forged.witness),bindings=memory.poles(fp.start),sb=memory.poles(bindings.start),eb=memory.poles(bindings.end),badWitness=memory.ensure(memory.ensure(memory.ensure(f.startRole,eb.end),memory.ensure(f.endRole,sb.end)),fp.end),bad=realization(memory,free,[badWitness,ws[1]!.witness,ws[2]!.witness]);same(run(memory,compile(memory,f,request(memory,K,forward.rule,bad))).length,0,"A58 forged decomposition ZERO");
  const foreignEq=memory.ensure(forward.equations[0]!,b.C),badEqWitness=memory.ensure(memory.poles(ws[0]!.witness).start,foreignEq),badEq=realization(memory,free,[badEqWitness,ws[1]!.witness,ws[2]!.witness]);same(run(memory,compile(memory,f,request(memory,K,forward.rule,badEq))).length,0,"A58 proof/equation mismatch ZERO");
  const selected=request(memory,K,forward.rule,valid),p=compile(memory,f,selected),frozen=p.E0;memory.ensure(ws[0]!.equation,b.C);same(p.E0,frozen,"A58 ambient projection-like Link inert");same(run(memory,p)[0],valid,"A58 ambient physical existence inert");
}
function staticGuards():void{const root=resolve(process.cwd(),".."),own=readFileSync(join(root,"ts/test/research-v013-proof-carried-equation-start-a58.test.ts"),"utf8"),a47=readFileSync(join(root,"ts/test/research-v013-proof-carried-start-projection-a47.test.ts"),"utf8"),a57=readFileSync(join(root,"ts/test/research-v013-projected-role-coverage-a57.test.ts"),"utf8");const core=own.slice(own.indexOf("function readEquationEvidence("),own.indexOf("\ninterface OneCheck",own.indexOf("function readEquationEvidence(")));for(const x of ["memory.poles(equation","memory.poles(eq).start","appendMappedSequence","roleCoverage","deriveSemanticContract","freeRoles","constrainedTargets","memory.find("])assert(!core.includes(x),`A58 semantic projection excludes ${x}`);assert(a47.includes("RECEIVER_TARGET_POLE_READS=0"),"A58 inherits A47 no-target-pole principle");assert(a57.includes("START_PROJECTION=HOST_GENERIC_RESIDUAL"),"A58 attacks exact A57 residual");}
function main():void{exercise(new Memory(),false);exercise(new Memory(),true);staticGuards();console.log(["MTS v0.13 A58: PROOF_CARRIED_EQUATION_START=GREEN_SCOPED_RESEARCH","EQUATION_TARGET_POLE_READS=0 MATERIALIZED_ROLE_COVERAGE=0","REALIZATION_EQUATIONS=DECOMPOSITION_WITNESSES","WITNESS_VALIDATION=ROLE_ROLE_RECONSTRUCTED_EQUATION_CANONICAL_GATES","VALID_COVERAGE_CHECKS=22 PROOF_GATES=9","FORGED_DECOMPOSITION=ZERO PROOF_EQUATION_MISMATCH=ZERO AMBIENT_PHYSICAL_EXISTENCE=INERT","DIRECT_AUTHORITY=K_TO_RULE_TO_REALIZATION A21_RUNTIME=UNCHANGED","WITNESS_SOURCE=CONSTRUCTION_TIME_RESIDUAL","NEXT_BOUNDARY=A59_WITNESSED_EQUATION_CONSTRUCTION_SOURCE","A35_PUBLICATION_EXISTENCE=RESIDUAL GLOBAL_E2=OPEN GLOBAL_E3=OPEN GLOBAL_E4=OPEN","FULL_SELF_HOSTED=FALSE V013_NOT_ACCEPTED PRODUCTION_UNCHANGED"].join(" "));}
main();