import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { Memory, ensureRootBasis, type LinkHandle, type RootBasis } from "../src/memory.js";

function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(`v0.13 A61 application producer classification: ${m}`);}
function same<T>(a:T,e:T,m:string):void{assert(Object.is(a,e),`${m}: values differ`);}
function expectThrows(fn:()=>void,m:string):void{let threw=false;try{fn();}catch{threw=true;}assert(threw,m);}
function freezeChain(memory:Memory,values:readonly LinkHandle[]):LinkHandle{let body=memory.root;for(let i=values.length-1;i>=0;i-=1)body=memory.ensure(values[i]!,body);return memory.ensureStartSelfClosed(body);}
function readChain(memory:Memory,envelope:LinkHandle,kind:string):readonly LinkHandle[]{const e=memory.poles(envelope);assert(e.start===envelope&&e.end!==envelope,`A21 ${kind} envelope`);const out:LinkHandle[]=[],seen=new Set<LinkHandle>();let cursor=e.end;while(cursor!==memory.root){assert(!seen.has(cursor),`A21 ${kind} cycle`);seen.add(cursor);const p=memory.poles(cursor);out.push(p.start);cursor=p.end;}return Object.freeze(out);}
function step(memory:Memory,executionRoot:LinkHandle,schedule:"forward"|"reverse"):LinkHandle{const execution=memory.poles(executionRoot),context=execution.start,frontierEnvelope=execution.end;const authorityEnvelope=memory.poles(context).end,continuations=[...readChain(memory,authorityEnvelope,"authority")],occurrences=[...readChain(memory,frontierEnvelope,"frontier")];if(schedule==="reverse")occurrences.reverse();let nextBody=memory.root;for(const occurrence of occurrences){const truth=memory.poles(memory.poles(occurrence).end);assert(truth.start===context,"A21 occurrence carries current-context truth");for(const continuation of continuations){const p=memory.poles(continuation);if(p.start!==truth.end)continue;const nextTruth=memory.ensure(context,p.end),childOccurrence=memory.ensure(occurrence,nextTruth);nextBody=memory.ensure(childOccurrence,nextBody);}}return memory.ensure(context,memory.ensureStartSelfClosed(nextBody));}
function frontierTruthEnds(memory:Memory,E:LinkHandle):readonly LinkHandle[]{const ep=memory.poles(E),out:LinkHandle[]=[];for(const occurrence of readChain(memory,ep.end,"frontier")){const truth=memory.poles(memory.poles(occurrence).end);same(truth.start,ep.start,"A61 frontier context");out.push(truth.end);}return Object.freeze(out);}

interface CurrentOccurrence{readonly context:LinkHandle;readonly currentValue:LinkHandle;readonly history:readonly LinkHandle[];}
function readCurrentOccurrence(memory: Memory, head: LinkHandle): CurrentOccurrence {
  const seen=new Set<LinkHandle>();
  const reversed:LinkHandle[]=[];
  let cursor=head;
  let context:LinkHandle|undefined;

  while(true){
    assert(!seen.has(cursor),"A33 occurrence ancestry cycle");
    seen.add(cursor);
    const occurrence=memory.poles(cursor);
    const value=occurrence.end;
    const vp=memory.poles(value);
    if(context===undefined) context=vp.start;
    else same(vp.start,context,"A33 occurrence history keeps one context");
    reversed.push(value);
    if(occurrence.start===memory.root) break;
    cursor=occurrence.start;
  }

  assert(context!==undefined,"A33 current occurrence context");
  reversed.reverse();
  return Object.freeze({
    context,
    currentValue:memory.poles(head).end,
    history:Object.freeze(reversed),
  });
}

interface Frame{readonly startRole:LinkHandle;readonly endRole:LinkHandle;}
function frame(memory:Memory,b:RootBasis):Frame{const whole=memory.ensure(b.L,b.L),startRole=memory.ensureStartSelfClosed(whole),endRole=memory.ensureEndSelfClosed(whole);assert(startRole!==endRole,"A61 frame roles distinct");return Object.freeze({startRole,endRole});}
function decompositionWitness(memory:Memory,f:Frame,node:LinkHandle,leftTemplate:LinkHandle,rightTemplate:LinkHandle):LinkHandle{const lb=memory.ensure(f.startRole,leftTemplate),rb=memory.ensure(f.endRole,rightTemplate);return memory.ensure(memory.ensure(lb,rb),node);}
function readyOccurrence(memory:Memory,previous:LinkHandle,context:LinkHandle,witness:LinkHandle,leftTemplate:LinkHandle,rightTemplate:LinkHandle,leftValue:LinkHandle,rightValue:LinkHandle):LinkHandle{const environment=memory.ensure(memory.ensure(leftTemplate,leftValue),memory.ensure(rightTemplate,rightValue));const ready=memory.ensure(witness,environment);return memory.ensure(previous,memory.ensure(context,ready));}

interface ApplicationProducer{produce(memory:Memory,currentOccurrence:LinkHandle):LinkHandle;}
function canonicalSelection(memory:Memory,currentOccurrence:LinkHandle):LinkHandle{const current=readCurrentOccurrence(memory,currentOccurrence),value=memory.poles(current.currentValue),ready=memory.poles(value.end),witness=ready.start,environment=ready.end,node=memory.poles(witness).end,application=memory.ensure(node,environment),proof=memory.ensure(environment,application),truth=memory.ensure(current.context,application);return memory.ensure(witness,memory.ensure(proof,truth));}
function directProducer():ApplicationProducer{return Object.freeze({produce:(memory:Memory,current:LinkHandle)=>canonicalSelection(memory,current)});}
function idempotentProducer():ApplicationProducer{return Object.freeze({produce(memory:Memory,current:LinkHandle){const a=canonicalSelection(memory,current),b=canonicalSelection(memory,current);same(a,b,"A61 idempotent canonical formation");return b;}});}
function noisyProducer():ApplicationProducer{return Object.freeze({produce(memory:Memory,current:LinkHandle){const cp=memory.poles(current);memory.ensure(cp.start,cp.start);memory.ensure(cp.end,cp.end);return canonicalSelection(memory,current);}});}
function swappedProducer():ApplicationProducer{return Object.freeze({produce(memory:Memory,current:LinkHandle){const c=readCurrentOccurrence(memory,current),value=memory.poles(c.currentValue),ready=memory.poles(value.end),witness=ready.start,ep=memory.poles(ready.end),environment=memory.ensure(ep.end,ep.start),node=memory.poles(witness).end,application=memory.ensure(node,environment),proof=memory.ensure(environment,application),truth=memory.ensure(c.context,application);return memory.ensure(witness,memory.ensure(proof,truth));}});}
function foreignNodeProducer(foreign:LinkHandle):ApplicationProducer{return Object.freeze({produce(memory:Memory,current:LinkHandle){const c=readCurrentOccurrence(memory,current),value=memory.poles(c.currentValue),ready=memory.poles(value.end),witness=ready.start,environment=ready.end,application=memory.ensure(foreign,environment),proof=memory.ensure(environment,application),truth=memory.ensure(c.context,application);return memory.ensure(witness,memory.ensure(proof,truth));}});}
function mismatchProducer(foreign:LinkHandle):ApplicationProducer{return Object.freeze({produce(memory:Memory,current:LinkHandle){const c=readCurrentOccurrence(memory,current),value=memory.poles(c.currentValue),ready=memory.poles(value.end),witness=ready.start,environment=ready.end,node=memory.poles(witness).end,application=memory.ensure(node,environment),proof=memory.ensure(environment,application),truth=memory.ensure(c.context,memory.ensure(foreign,environment));return memory.ensure(witness,memory.ensure(proof,truth));}});}

interface EqualityCheck{readonly gate:LinkHandle;readonly query:LinkHandle;}
function equalityCheck(memory:Memory,stage:LinkHandle,expected:LinkHandle,actual:LinkHandle):EqualityCheck{const es=memory.ensure(stage,expected),as=memory.ensure(stage,actual),gate=memory.ensureStartSelfClosed(es);return Object.freeze({gate,query:memory.ensure(gate,as)});}
interface ApplicationCandidate{readonly parentContext:LinkHandle;readonly startValue:LinkHandle;readonly endValue:LinkHandle;readonly checks:readonly EqualityCheck[];}
function deriveApplicationCandidate(memory:Memory,f:Frame,selection:LinkHandle):ApplicationCandidate{const selected=memory.poles(selection),witness=selected.start,inner=memory.poles(selected.end),proof=memory.poles(inner.start),truth=memory.poles(inner.end),environment=proof.start,proofApplication=proof.end,parentContext=truth.start,truthApplication=truth.end;const wp=memory.poles(witness),wb=memory.poles(wp.start),wl=memory.poles(wb.start),wr=memory.poles(wb.end),node=wp.end,leftTemplate=wl.end,rightTemplate=wr.end,env=memory.poles(environment),lb=memory.poles(env.start),rb=memory.poles(env.end),startValue=lb.end,endValue=rb.end,expectedApplication=memory.ensure(node,environment),reconstructedNode=memory.ensure(leftTemplate,rightTemplate);let stage=memory.ensure(selection,memory.root);const check=(e:LinkHandle,a:LinkHandle):EqualityCheck=>{stage=memory.ensure(stage,memory.ensure(e,a));return equalityCheck(memory,stage,e,a);};return Object.freeze({parentContext,startValue,endValue,checks:Object.freeze([check(proofApplication,truthApplication),check(expectedApplication,proofApplication),check(leftTemplate,lb.start),check(rightTemplate,rb.start),check(f.startRole,wl.start),check(f.endRole,wr.start),check(reconstructedNode,node)])});}
interface PairConstructor{construct(start:LinkHandle,end:LinkHandle):LinkHandle;}
function pairConstructor(memory:Memory):PairConstructor{return Object.freeze({construct:(start:LinkHandle,end:LinkHandle)=>memory.ensure(start,end)});}
interface ValidationProgram{readonly E0:LinkHandle;readonly depth:number;}
function compileValidation(memory:Memory,c:ApplicationCandidate,result:LinkHandle):ValidationProgram{const transitions=c.checks.map((x,i)=>memory.ensure(x.gate,c.checks[i+1]?.query??result)),K=memory.ensure(c.parentContext,freezeChain(memory,transitions)),seed=memory.ensure(K,c.checks[0]!.query);return Object.freeze({E0:memory.ensure(K,freezeChain(memory,[memory.ensure(memory.root,seed)])),depth:c.checks.length});}
function executeSelection(memory:Memory,f:Frame,selection:LinkHandle):readonly LinkHandle[]{const c=deriveApplicationCandidate(memory,f,selection),physical=pairConstructor(memory).construct(c.startValue,c.endValue),program=compileValidation(memory,c,physical);let current=program.E0;for(let i=0;i<program.depth;i+=1)current=step(memory,current,"forward");return frontierTruthEnds(memory,current);}

function setup(memory:Memory,b:RootBasis,f:Frame):{readonly context:LinkHandle;readonly witness:LinkHandle;readonly leftTemplate:LinkHandle;readonly rightTemplate:LinkHandle;readonly leftValue:LinkHandle;readonly rightValue:LinkHandle;}{const marker=memory.ensure(b.U,b.U),leftTemplate=memory.ensure(memory.ensure(b.O,marker),marker),rightTemplate=memory.ensure(leftTemplate,marker),node=memory.ensure(leftTemplate,rightTemplate),witness=decompositionWitness(memory,f,node,leftTemplate,rightTemplate),leftValue=memory.ensure(b.C,b.U),rightValue=memory.ensure(b.O,b.L),context=memory.ensure(b.R,b.U);return Object.freeze({context,witness,leftTemplate,rightTemplate,leftValue,rightValue});}
function exercise(memory:Memory,noise:boolean):void{const b=ensureRootBasis(memory);if(noise)memory.ensure(memory.ensure(b.U,b.C),b.O);const f=frame(memory,b),s=setup(memory,b,f),occ0=readyOccurrence(memory,memory.root,s.context,s.witness,s.leftTemplate,s.rightTemplate,s.leftValue,s.rightValue);const expectedSelection=canonicalSelection(memory,occ0);for(const producer of [directProducer(),idempotentProducer(),noisyProducer()]){const selection=producer.produce(memory,occ0);same(selection,expectedSelection,"A61 conforming producer canonical selection");const out=executeSelection(memory,f,selection);same(out.length,1,"A61 conforming producer singleton");same(out[0],memory.ensure(s.leftValue,s.rightValue),"A61 conforming producer exact result");}
const foreign=memory.ensure(s.witness,b.C);for(const producer of [swappedProducer(),foreignNodeProducer(foreign),mismatchProducer(foreign)])same(executeSelection(memory,f,producer.produce(memory,occ0)).length,0,"A61 malformed producer semantic ZERO");
const altLeft=memory.ensure(s.leftValue,b.C),altRight=memory.ensure(s.rightValue,b.C),occ1=readyOccurrence(memory,occ0,s.context,s.witness,s.leftTemplate,s.rightTemplate,altLeft,altRight);same(directProducer().produce(memory,occ0),expectedSelection,"A61 ambient newer occurrence does not replace selected head");const out1=executeSelection(memory,f,directProducer().produce(memory,occ1));same(out1.length,1,"A61 advanced current occurrence singleton");same(out1[0],memory.ensure(altLeft,altRight),"A61 advanced head selects newer operands");
const foreignContext=memory.ensure(b.O,b.C),mixed=readyOccurrence(memory,occ0,foreignContext,s.witness,s.leftTemplate,s.rightTemplate,altLeft,altRight);expectThrows(()=>{readCurrentOccurrence(memory,mixed);},"A61 mixed occurrence context rejected");
}

function staticGuards():void{const root=resolve(process.cwd(),".."),own=readFileSync(join(root,"ts/test/research-v013-application-producer-classification-a61.test.ts"),"utf8"),a33=readFileSync(join(root,"ts/test/research-v013-generic-current-occurrence-a33.test.ts"),"utf8"),a60=readFileSync(join(root,"ts/test/research-v013-rule-proof-application-reconnect-a60.test.ts"),"utf8");const producer=own.slice(own.indexOf("function canonicalSelection("),own.indexOf("\nfunction directProducer(",own.indexOf("function canonicalSelection(")));for(const x of ["readStructuralRule","readStructuralRoleDictionary","schedule","pending","dictionary","memory.find(","if(","for(","switch("])assert(!producer.includes(x),`A61 canonical producer excludes semantic/scheduling branch ${x}`);const x=own.slice(own.indexOf("function readCurrentOccurrence("),own.indexOf("\ninterface Frame",own.indexOf("function readCurrentOccurrence("))),y=a33.slice(a33.indexOf("function readCurrentOccurrence("),a33.indexOf("\nfunction exercise(",a33.indexOf("function readCurrentOccurrence(")));same(x.replace(/\s+/g,""),y.replace(/\s+/g,""),"A61 current-occurrence reader source-identical A33");assert(a60.includes("RULE_TO_SELECTED_APPLICATION_PRODUCTION=GENERIC_E4_ORCHESTRATION_RESIDUAL"),"A61 attacks exact A60 residual");const constructorSlice=own.slice(own.indexOf("interface PairConstructor"),own.indexOf("\ninterface ValidationProgram",own.indexOf("interface PairConstructor"))).toLowerCase();for(const x of ["schema","template","role","context","truth","application","proof","candidate"])assert(!constructorSlice.includes(x),`A61 preserves A54 constructor boundary ${x}`);const normal=producer.toLowerCase();for(const x of ["rule","admission","candidate type","truth value"])assert(!normal.includes(x),`A61 normalizer excludes semantic authority term ${x}`);}
function main():void{exercise(new Memory(),false);exercise(new Memory(),true);staticGuards();console.log(["MTS v0.13 A61: APPLICATION_PRODUCER_CLASSIFICATION=GREEN_SCOPED_RESEARCH","CURRENT_OCCURRENCE_HEAD=A33_E4_EXECUTOR_STATE","PRODUCER_INPUT=CURRENT_OCCURRENCE_ONLY RULE_SCHEDULER_ARGUMENTS=0","APPLICATION_CARRIER_FORMATION=DETERMINISTIC_CANONICAL_NORMAL_FORM","CONFORMING_PRODUCERS=3 CANONICAL_SELECTION_IDENTITY=INVARIANT","MALFORMED_PRODUCERS=3 SEMANTIC_ZERO_BY_A53_STYLE_GATES","AMBIENT_NEWER_OCCURRENCE=INERT UNTIL_HEAD_ADVANCE","HEAD_ADVANCE=SELECTS_NEW_READY_VALUE","MIXED_CONTEXT_HISTORY=REJECTED","E2_SEMANTIC_SOURCE_IN_PRODUCER=0","FORMATION_CLASSIFICATION=E3_SCOPED_BOUNDARY EXECUTION_SELECTION=E4_SCOPED_BOUNDARY","RULE_AUTHORSHIP_ADMISSION=E2_E3_RESIDUAL A35_PUBLICATION_EXISTENCE=RESIDUAL","GLOBAL_E2=OPEN GLOBAL_E3=OPEN GLOBAL_E4=OPEN FULL_SELF_HOSTED=FALSE","NEXT_BOUNDARY=A62_REASSESS_RULE_AUTHORSHIP_ADMISSION_AND_A35","V013_NOT_ACCEPTED PRODUCTION_UNCHANGED"].join(" "));}
main();
